name: Deploy Kubernetes Manifest
description: "Composite action to deploy Kubernetes manifest to AKS"
inputs:
  aks_cluster_name:
    description: 'Nazwa klastra AKS'
    required: true
  aks_resource_group:
    description: 'Resource Group klastra AKS'
    required: true
  azure_credentials_json:
    description: 'Azure credentials JSON'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials_json }}

    - name: Set up Kubectl
      shell: bash
      run: az aks install-cli

    - name: Get AKS Credentials
      shell: bash
      run: az aks get-credentials --name ${{ inputs.aks_cluster_name }} --overwrite-existing --resource-group ${{ inputs.aks_resource_group }}

    - name: Deploy Kubernetes Manifest
      shell: bash
      run: |
        kubectl get nodes
        # kubectl delete -f ./k8s/pod.yaml
        kubectl apply -f ./k8s/ajpyapp-deployment.yaml

    - name: Poczekaj 10s i Test Kubernetes Deployment
      shell: bash
      run: |
        sleep 10
        kubectl get all -n dev

